[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1GnPVzXV3Z7J2U5BewdWzDFVZo5ZXzqmg9QDr9CN78Pc/edit?usp=sharing"



[connections.mysql]
dialect = "mysql"
host = "mysql-1409-kunalsharan1409-54fa.d.aivencloud.com"
port = 10676
database = "defaultdb"
username = "avnadmin"
password = "AVNS_xgF6lLmxsG1bwqJQJcr"